---
title: "CE4-Covid19"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style>                     
.navbar {
  background-color:black;
  border-color:grey;
}
.navbar-brand {
color:white!important;
}
.bg {
  background-color: black;
}
.body {
  color: black;
}
</style>

```{r libraries}
library(flexdashboard)
library(rio)
library(tidyverse)
library(XML)
library(httr)
library(RCurl)
library(sf)
library(lubridate)
library(leaflet)
library(colorspace)
library(DT)
library(zoo)
library(slider)
library(plotly)
```

```{r imports}
dat <- rio::import("https://github.com/jincio/COVID_19_PERU/blob/master/docs/reportes_minsa.xlsx?raw=true")

deps <- rio::import("https://github.com/jincio/COVID_19_PERU/blob/master/docs/reportes_minsa.xlsx?raw=true", sheet = 2)

pop <- read_csv("data/peru_pop_stratum.csv") %>%
  group_by(dep_adm1) %>%
  dplyr::summarise(pop = sum(N)) %>%
  mutate(REGION = toupper(dep_adm1))
```


```{r dm maps, include=FALSE}
c.date <- max(deps$Fecha)

dep <- 
  deps %>% 
  dplyr::select(dat = Fecha,
                dep = REGION, 
                pos = Positivos_totales, 
                pos.imp = PositivosImputados_totales,
                pas =Fallecidos, 
                smp =Total_muestras) %>% 
  mutate(pas = pas %>% if_else(is.na(.), 0, .)) %>% 
  group_by(dep) %>% 
  mutate(pos.lag = lag(pos, n = 1),
         pos.imp.lag = lag(pos.imp, n = 1),
         pas.lag = lag(pas, n = 1),
         smp.lag = lag(smp, n = 1)) %>%
  filter(dat == c.date) %>% 
  mutate(pos.new = abs(pos - pos.lag),
         pos.imp.new = abs(pos.imp - pos.imp.lag),
         pas.new = abs(pas - pas.lag),
         smp.new = abs(smp - smp.lag),
         ratio.new = signif(pos.new/smp.new), digits = 3)
  

## Regions geometry
shp <- st_read("Limite_departamental", stringsAsFactors = F)
shp <- shp %>% 
  st_transform(4326) %>% 
  select(Departamento = NOMBDEP)

# Append
dep <- merge(dep, shp, by.y = 'Departamento', by.x = 'dep', all.x = T)
dep <- st_as_sf(dep, sf_column_name = 'geometry')

## aes
pal_fun <- colorQuantile("YlOrRd", NULL, n = 5)
pal_smp <- colorQuantile("Blues", NULL, n = 5)

labels.total <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$pos) %>% lapply(htmltools::HTML)

labels.new <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$pos.new) %>% lapply(htmltools::HTML)

labels.pas <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$pas) %>% lapply(htmltools::HTML)

labels.smp <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$smp) %>% lapply(htmltools::HTML)

labels.smp.new <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$smp.new) %>% lapply(htmltools::HTML)

labels.ratio <- sprintf(
      "<strong>%s</strong><br/<strong>Value: </strong>%s",
      dep$dep, dep$ratio.new) %>% lapply(htmltools::HTML)
```

```{r dm plotly}
dat0 <- deps %>%
  dplyr::select(REGION, Fecha, PositivosImputados_totales, Positivos_PR) %>% 
  inner_join(pop, by="REGION") %>%
  arrange(REGION, Fecha) %>%
  group_by(REGION) %>%
  dplyr::mutate(new = PositivosImputados_totales - lag(PositivosImputados_totales, default = 0),
         mav_new = slide_dbl(new, ~mean(.x, na.rm = TRUE), .before = 6),
         pmav_new = 1000000*mav_new/pop,
         max = max(mav_new)) 

today <- ymd(Sys.Date())

dat1 <- dat %>%
  dplyr::mutate(pos_new = Positivos-lag(Positivos,default = 0),
                des_new = Descartados-lag(Descartados,default = 0),
                Dia = ymd(Dia)) %>%
  group_by(Dia) %>%
  dplyr::summarise(pos_new = sum(pos_new), des_new = sum(des_new)) %>%
  dplyr::mutate(cum_pos = cumsum(pos_new),
                tot_pruebas = pos_new+des_new,
                tm = difftime(today, Dia , units = c("days")))


dat2 <- dat1 %>%
  dplyr::mutate(neg_new = tot_pruebas-pos_new) %>%
  dplyr::select(Dia, pos_new, neg_new) %>%
  dplyr::rename(Positivo = pos_new, Negativo = neg_new) %>%
  gather(res, count, -Dia) %>%
  uncount(count)

dat3 <- dat1 %>%
  dplyr::mutate(new = cum_pos - lag(cum_pos, default = 0),
                mav_new = slide_dbl(new, ~mean(.x, na.rm = TRUE), .before = 6),
                max = max(mav_new)
  )

dat4 <- dat0 %>%
  select(Fecha,PositivosImputados_totales,REGION,new) %>%
  spread(REGION, new) %>%
  mutate(tm = difftime(today, Fecha , units = c("days")))
```


# Regional {.bg}

Column 1 {.tabset data-width=350} 
-------------------------------------

### Casos totales 

```{r}
pal.cases <- colorNumeric( palette="YlOrRd", domain = log(dep$pos), na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor = pal.cases(log(dep$pos)),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.total,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal = pal.cases, values = log(dep$pos), title= 'Log de casos')
```

### Casos nuevos 

```{r}

pal.newcases <- colorNumeric( palette="YlOrRd", domain = log(dep$pos.new), na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor = pal.newcases(log(dep$pos.new)),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.new,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal=pal.newcases, values = log(dep$pos.new), title= ' Log de casos')
```

### Fallecidos 

```{r}
pal.pas <- colorNumeric( palette="YlOrRd", domain = dep$pas, na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor = pal.pas(dep$pas),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.pas,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal=pal.pas, values = dep$pas, title= 'Cantidad de fallecidos')
```

### Pruebas realizadas 

```{r}
pal.smp <- colorNumeric( palette="Blues", domain = log(dep$smp), na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor = pal.smp(log(dep$smp)),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.smp,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal=pal.smp, values = log(dep$smp), title= 'Log de pruebas totales')
```

### Nuevas pruebas realizadas 

```{r}
pal.smpnew <-  colorNumeric( palette="Blues", domain = log(dep$smp.new), na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor =pal.smpnew(log(dep$smp.new)),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.smp.new,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal=pal.smpnew, values = log(dep$smp.new), title= 'Log de pruebas nuevas')
```

### Tasa de positivos nuevos

```{r}
pal.ratio <-  colorNumeric( palette="Blues", domain = dep$ratio.new, na.color="transparent")

leaflet(dep) %>%
  addTiles(urlTemplate = 'http://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png') %>%
  addPolygons(fillColor = pal.ratio(dep$ratio.new),
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels.ratio,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend("bottomleft", pal=pal.ratio, values = dep$ratio.new, title= 'Tasa de positivos nuevos')
```

Column 2 {.tabset data-width=400}
-------------------------------------

### Lineal

```{r, message=F, warning=F, class.output="scroll-100"}
plot_ly(dat1) %>%
  add_trace(x = ~Dia, y = ~pos_new, 
            type = 'bar', name = 'Casos Nuevos',
            marker = list(color = 'rgb(128,160,53)'), 
            text = paste(dat1$tm, "días desde hoy"),
            hovertemplate = paste('<b>Fecha</b>: %{x}',
                                  '<br><b>Nuevos Casos:</b> %{y}</br>',
                                  '<b>%{text}</b>'))%>% 
  add_trace(x = ~Dia, y = ~cum_pos, 
            type = 'scatter',
            mode = 'lines+markers', 
            name = 'Casos Acumulados', 
            yaxis = 'y2',
            line = list(color = 'rgb(35,104,99)'), 
            marker = list(color = 'rgb(35,104,99)'),
            text = paste(dat1$tm, "días desde hoy"),
            hovertemplate = ~paste('<b>Fecha</b>: %{x}',
                                   "<br><b>Casos Acumulados: %{y}</b></br>",
                                   '<b>%{text}</b>')) %>% 
  layout(title = 'Casos nuevos y acumulados de Perú',
         xaxis = list(title = "Fecha"),
         yaxis = list(side = 'left', title = 'Casos Nuevos por día', showgrid = FALSE, zeroline = FALSE),
         yaxis2 = list(side = 'right', overlaying = "y", title = 'Casos acumulados por día', showgrid = FALSE, zeroline = FALSE))%>%
  add_segments(x = "2020-04-08", xend = "2020-04-08", 
               y = 0, yend=max(dat1$pos_new),
               text="2020-04-08",name="Inicio de P.R's",
               hovertemplate = paste('<b>%{text}</b>'),
               legendgroup = 'group2',
               width=2, 
               line = list(color = "rgb(166,55,63)", 
                           width = 3, 
                           dash = "dot")
  )
```

### Logaritmico

```{r, message=F, warning=F, class.output="scroll-100"}
plot_ly(dat1) %>%
  add_trace(x = ~Dia, y = ~pos_new, 
            type = 'bar', name = 'Casos Nuevos',
            marker = list(color = 'rgb(128,160,53)'), 
            text = paste(dat1$tm, "días desde hoy"),
            hovertemplate = paste('<b>Fecha</b>: %{x}',
                                  '<br><b>Nuevos Casos:</b> %{y}</br>',
                                  '<b>%{text}</b>'))%>% 
  add_trace(x = ~Dia, y = ~cum_pos, 
            type = 'scatter',
            mode = 'lines+markers', 
            name = 'Casos Acumulados', 
            yaxis = 'y2',
            line = list(color = 'rgb(35,104,99)'), 
            marker = list(color = 'rgb(35,104,99)'),
            text = paste(dat1$tm, "días desde hoy"),
            hovertemplate = ~paste('<b>Fecha</b>: %{x}',
                          "<br><b>Casos Acumulados: %{y}</b></br>",
                          '<b>%{text}</b>')) %>% 
  layout(title = 'Casos nuevos y acumulados de Perú',
         xaxis = list(title = "Fecha"),
         yaxis = list(side = 'left', title = 'Casos Nuevos por día', showgrid = FALSE, zeroline = FALSE),
         yaxis2 = list(side = 'right', overlaying = "y", type = "log",
                       title = 'Casos acumulados por día', 
                       showgrid = FALSE, zeroline = FALSE))%>%
  add_segments(x = "2020-04-08", xend = "2020-04-08", 
               y = 0, yend=max(dat1$pos_new),
               text="2020-04-08",name="Inicio de P.R's",
               hovertemplate = paste('<b>%{text}</b>'),
               legendgroup = 'group2',
               width=2, 
              line = list(color = "rgb(166,55,63)", 
                          width = 3, 
                          dash = "dot")
               )
```

Column 3 {data-width=250}
-------------------------------------

### Datos actualizados al:
```{r}
valueBox(c.date, icon = "fa-calendar")
```

### Total de casos

```{r}
valueBox(sum(dep$pos), icon = "fa-pencil")
```

### Nuevos casos

```{r}
valueBox(sum(dep$pos.new), icon = "fa-pencil")
```

### Column 2 - Chart 1
```{r}
DT::datatable(dep %>% 
                select(Region = dep,
                       `Total de casos` = pos,
                       `Total de fallecidos` = pas,
                       `Total de muestras` = smp) %>% 
                arrange(desc(`Total de casos`)) %>% 
                st_set_geometry(NULL), 
              options = list(
                bPaginate = FALSE
))
```